# Table of Contents
 <p><div class="lev4 toc-item"><a href="#Question-marks" data-toc-modified-id="Question-marks-0001"><span class="toc-item-num">0.0.0.1&nbsp;&nbsp;</span>Question marks</a></div>

In [1]:
import numpy as np

#### Glossary:
- Vector

#### Question marks
- np.nonzero()
- np.unravel_index()


1. Create a null vector of size 10

In [14]:
# np.zeros --> Return a new array of given shape and type, filled with zeros.
z = np.zeros(10, dtype=int)
z

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.zeros((10, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

2. Create a null vector of size 10 but the fifth value which is 1

In [26]:
z = np.zeros(10, dtype=int)
z

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
z[4] = 1
z

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

3. Create a vector with values ranging from 10 to 49

In [29]:
# np.arange --> Return evenly spaced values within a given interval.
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Reverse a vector (first element becomes last)

In [30]:
Z = np.arange(10)
Z[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

5. Create a 3x3 matrix with values ranging from 0 to 8

In [39]:
# Reshape --> Gives a new shape to an array without changing its data.
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

6. Find indices of non-zero elements from [1,2,0,0,4,0]

In [54]:
# I DON'T UNDERSTAND THIS ONE
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

7. Create a 3x3 identity matrix <br><br>


In linear algebra, the identity matrix, or sometimes ambiguously called a unit matrix, of size n is the n × n square matrix with ones on the main diagonal and zeros elsewhere.

In [55]:
# np.eye --> Return a 2-D array with ones on the diagonal and zeros elsewhere.
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

8. Create a 10x10 array with random values and find the minimum and maximum values

In [59]:
rand_arr = np.random.random((10,10))
rand_arr

array([[0.77601312, 0.31730465, 0.62646417, 0.97965138, 0.15675778,
        0.77103815, 0.33931016, 0.23019579, 0.27196316, 0.61816947],
       [0.42323156, 0.7213773 , 0.56169584, 0.04384808, 0.84905416,
        0.75070849, 0.82446935, 0.09087556, 0.41154953, 0.83555325],
       [0.73194586, 0.0295011 , 0.85729104, 0.245753  , 0.74856853,
        0.23438754, 0.46288301, 0.36787503, 0.50644169, 0.05654801],
       [0.76695422, 0.79634356, 0.97047666, 0.80985455, 0.61655178,
        0.97495074, 0.23844442, 0.87543079, 0.59693597, 0.95005052],
       [0.30973446, 0.19632496, 0.99272919, 0.03486484, 0.56162386,
        0.56328678, 0.6705981 , 0.42307423, 0.04654769, 0.96878066],
       [0.82907137, 0.58939345, 0.27134194, 0.20862568, 0.22184943,
        0.92516174, 0.38920657, 0.89645819, 0.86658623, 0.04733922],
       [0.12638016, 0.55713941, 0.67261035, 0.32456548, 0.73439488,
        0.04016591, 0.7728709 , 0.08797074, 0.91761978, 0.07078881],
       [0.47263678, 0.50638534, 0.2299845

In [74]:
print(rand_arr.max())
print(rand_arr.min())

0.9927291893442535
0.02950110118612259


9. Create a random vector of size 30 and find the mean value

In [76]:
z = np.random.random(30)
z.mean()

0.46533216277949235

10. Create a 2d array with 1 on the border and 0 inside

In [95]:
z = np.ones((10,10))
# rows, columns
z[1:-1, 1:-1] = 0
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

11. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [96]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [97]:
twobyfour = [
   [0,1,2,3], 
   [4,5,6,7]
]
 
np.unravel_index([0,7], (2,4))

(array([0, 1], dtype=int64), array([0, 3], dtype=int64))

    In plain English, when we run unravel_index in this example, we’re saying: “Get us the coordinates of the 0th and 7th elements of a 2-by-4 matrix.”
    I printed out, in the first line, the standard way 2-by-4 matrices are indexed where the first coordinate specifies the row. Verify for yourself that the 0th element has coordinate (row 0, column 0) and the 7th element has coordinate (row 1, column 3). unravel_index outputs the row coordinates together and the column coordinates together, so instead of returning ((0, 0), (1, 3)) , it returns ((0, 1), (0, 3)).
    Under the hood, unravel_index is just doing simple arithmetic to find quotients and remainders. But this logic is tedious and used frequently to select elements of matrices and Pandas Dataframes that it make sense to add it as a numpy function.

12. Create a checkerboard 8x8 matrix using the tile function

In [105]:
# simply repeats the numbers of elements in an array. If you have an array, like so [1,2,3],
# then np.tile([1,2,3], 2) will repeat the elements twice and make a new array.
np.tile( np.array([[0,1,],[1,0]]), (2,2))

array([[0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0]])

13. Create a custom dtype that describes a color as four unisgned bytes (RGBA) 

In [106]:
color = np.dtype([('r', np.ubyte, 1),
                ('g', np.ubyte, 1),
                 ('b', np.ubyte, 1),
                 ('a', np.ubyte, 1),])

In [107]:
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

14. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [108]:
np.dot(np.ones((5,3)), np.ones((3,2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])