# Table of Contents
 <p><div class="lev3 toc-item"><a href="#Basic:" data-toc-modified-id="Basic:-001"><span class="toc-item-num">0.0.1&nbsp;&nbsp;</span>Basic:</a></div><div class="lev2 toc-item"><a href="#Numpy-array" data-toc-modified-id="Numpy-array-01"><span class="toc-item-num">0.1&nbsp;&nbsp;</span>Numpy array</a></div><div class="lev3 toc-item"><a href="#Creating-a-numpy-array" data-toc-modified-id="Creating-a-numpy-array-011"><span class="toc-item-num">0.1.1&nbsp;&nbsp;</span>Creating a numpy array</a></div><div class="lev3 toc-item"><a href="#Convert-array" data-toc-modified-id="Convert-array-012"><span class="toc-item-num">0.1.2&nbsp;&nbsp;</span>Convert array</a></div><div class="lev4 toc-item"><a href="#Convert-datatype-of-array" data-toc-modified-id="Convert-datatype-of-array-0121"><span class="toc-item-num">0.1.2.1&nbsp;&nbsp;</span>Convert datatype of array</a></div><div class="lev4 toc-item"><a href="#Convert-array-to-list" data-toc-modified-id="Convert-array-to-list-0122"><span class="toc-item-num">0.1.2.2&nbsp;&nbsp;</span>Convert array to list</a></div><div class="lev3 toc-item"><a href="#Inspecting-an-array" data-toc-modified-id="Inspecting-an-array-013"><span class="toc-item-num">0.1.3&nbsp;&nbsp;</span>Inspecting an array</a></div><div class="lev3 toc-item"><a href="#Extracting-specific-items-from-an-array" data-toc-modified-id="Extracting-specific-items-from-an-array-014"><span class="toc-item-num">0.1.4&nbsp;&nbsp;</span>Extracting specific items from an array</a></div><div class="lev3 toc-item"><a href="#Reversing-an-array" data-toc-modified-id="Reversing-an-array-015"><span class="toc-item-num">0.1.5&nbsp;&nbsp;</span>Reversing an array</a></div><div class="lev3 toc-item"><a href="#How-to-represent-missing-values-and-infinite?" data-toc-modified-id="How-to-represent-missing-values-and-infinite?-016"><span class="toc-item-num">0.1.6&nbsp;&nbsp;</span>How to represent missing values and infinite?</a></div><div class="lev3 toc-item"><a href="#compute-mean,-min,-max-on-the-ndarray" data-toc-modified-id="compute-mean,-min,-max-on-the-ndarray-017"><span class="toc-item-num">0.1.7&nbsp;&nbsp;</span>compute mean, min, max on the ndarray</a></div><div class="lev4 toc-item"><a href="#computing-the-minimum-and-maximum-values-row-wise-or-column-wise:" data-toc-modified-id="computing-the-minimum-and-maximum-values-row-wise-or-column-wise:-0171"><span class="toc-item-num">0.1.7.1&nbsp;&nbsp;</span>computing the minimum and maximum values row wise or column wise:</a></div><div class="lev3 toc-item"><a href="#Creating-a-new-array-from-an-existing-array" data-toc-modified-id="Creating-a-new-array-from-an-existing-array-018"><span class="toc-item-num">0.1.8&nbsp;&nbsp;</span>Creating a new array from an existing array</a></div><div class="lev3 toc-item"><a href="#Rashaping-an-array" data-toc-modified-id="Rashaping-an-array-019"><span class="toc-item-num">0.1.9&nbsp;&nbsp;</span>Rashaping an array</a></div><div class="lev3 toc-item"><a href="#Flattening-a-multi-dimensional-array" data-toc-modified-id="Flattening-a-multi-dimensional-array-0110"><span class="toc-item-num">0.1.10&nbsp;&nbsp;</span>Flattening a multi-dimensional array</a></div><div class="lev3 toc-item"><a href="#Creating-sequences,-repetitions-and-random-numbers" data-toc-modified-id="Creating-sequences,-repetitions-and-random-numbers-0111"><span class="toc-item-num">0.1.11&nbsp;&nbsp;</span>Creating sequences, repetitions and random numbers</a></div><div class="lev4 toc-item"><a href="#Sequence:" data-toc-modified-id="Sequence:-01111"><span class="toc-item-num">0.1.11.1&nbsp;&nbsp;</span>Sequence:</a></div><div class="lev3 toc-item"><a href="#Repeating-sequences" data-toc-modified-id="Repeating-sequences-0112"><span class="toc-item-num">0.1.12&nbsp;&nbsp;</span>Repeating sequences</a></div><div class="lev3 toc-item"><a href="#Generating-random-numbers" data-toc-modified-id="Generating-random-numbers-0113"><span class="toc-item-num">0.1.13&nbsp;&nbsp;</span>Generating random numbers</a></div><div class="lev3 toc-item"><a href="#Unique-items" data-toc-modified-id="Unique-items-0114"><span class="toc-item-num">0.1.14&nbsp;&nbsp;</span>Unique items</a></div>

In [1]:
import numpy as np

### Basic:

In [2]:
# Squared and square root:
x = np.square(3)
y = np.sqrt(x)
print(f'x = {x} and y = {y}')

x = 9 and y = 3.0


# Numpy array
- At the core, numpy provides the excellent ndarray objects, short for n-dimensional arrays. In a ‘ndarray’ object, aka ‘array’, you can store multiple items of the same data type. It is the facilities around the array object that makes numpy so convenient for performing math and data manipulations. 
- The key difference between an array and a list is, arrays are designed to handle vectorized operations while a python list is not. That means, if you apply a function it is performed on every item in the array, rather than on the whole array object.
- Another characteristic is that, once a numpy array is created, you cannot increase its size. To do so, you will have to create a new array. But such a behavior of extending the size is natural in a list.
- Unlike Python lists, a numpy array must have all items to be of the same data type. 
- An equivalent numpy array occupies much less space than a python list of lists.
- You may specify the datatype by setting the dtype argument. Some of the most commonly used numpy dtypes are: 'float', 'int', 'bool', 'str' and 'object'. To control the memory allocations you may choose to use one of ‘float32’, ‘float64’, ‘int8’, ‘int16’ or ‘int32’.

## Creating a numpy array<br>

#### Create an **1d array** from a list

In [3]:
list1 = [0,1,2,3,4]
np.array(list1)

array([0, 1, 2, 3, 4])

Create the array directly

In [4]:
np.array([0, 1, 2, 3, 4], dtype='int')

array([0, 1, 2, 3, 4])

#### Creating a **2d array** from a list of lists

In [5]:
list2 = [[0,1,2], [3,4,5], [6,7,8]]
np.array(list2)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Copy an array

In [95]:
a = np.array([1, 2, 3, 4])
b = np.copy(a)
print('b: ', b )

b:  [1 2 3 4]


## Array Methods

In [79]:
a = np.array((4, 3, 2, 1))

# sort - sorts a in place
a.sort()
print(f'sorted: {a}')

# sum
print('sum: ', a.sum())

# mean
print('mean: ', a.mean())

# max
print('max: ', a.max())

# argmax - returns the index of the maximal element
print('argmax: ', a.argmax())

# cumsum - cumulative sum of the elements of a
print('cumsum: ', a.cumsum())

# cumprod - cumulative product of the elements of a
print('cumprod: ', a.cumprod())

# variance
print('variance: ', a.var())

# standard deviation
print('standard deviation: ', a.std())

sorted: [1 2 3 4]
sum:  10
mean:  2.5
max:  4
argmax:  3
cumsum:  [ 1  3  6 10]
cumprod:  [ 1  2  6 24]
variance:  1.25
standard deviation:  1.118033988749895


## Array Methods on Two-Dimensional Arrays

In [93]:
arr2 = np.array([[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]], dtype='int')
arr2

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [5, 6, 7, 8]])

In [94]:
# mean
print("Mean value is: ", arr2.mean())

# max
print("Max value is: ", arr2.max())

# min
print("Min value is: ", arr2.min())

# column wise minimum
print("Column wise minimum: ", np.amin(arr2, axis=0))

# row wise minimum
print("Row wise minimum: ", np.amin(arr2, axis=1))

# column wise maximum
print("Column wise maximum: ", np.amax(arr2, axis=0))

# row wise maximum
print("Row wise maximum: ", np.amax(arr2, axis=1))

Mean value is:  4.5
Max value is:  8
Min value is:  1
Column wise minimum:  [1 2 3 4]
Row wise minimum:  [1 3 5]
Column wise maximum:  [5 6 7 8]
Row wise maximum:  [4 6 8]


## Operations on Arrays

In [89]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# adding
print(f'adding: A + B: {a + b}')

# multiplication
print(f'multiplication: A * B: {a * b}')

# adding scalar
print(f'adding scalar: A + 10: {a + 10}')

# scalar multiplication
print(f'scalar multiplication: A * 10: {a * 10}')

adding: A + B: [ 6  8 10 12]
multiplication: A * B: [ 5 12 21 32]
adding scalar: A + 10: [11 12 13 14]
scalar multiplication: A * 10: [10 20 30 40]


## Matrix Multiplication

In [91]:
# create two two-dimensional arrays of ones
A = np.ones((2, 2))
B = np.ones((2, 2))

A @ B

array([[2., 2.],
       [2., 2.]])

## Comparisons

In [101]:
z = np.array([2, 3])
y = np.array([2, 3])

# comparing two arrays
print('checking z and y for similarities: ', z == y)
print('checking z and y for differences: ', z != y)

# comparing against scalar
print('for each value is z, is the value equal to 3: ', z == 3 )

checking z and y for similarities:  [ True  True]
checking z and y for differences:  [False False]
for each value is z, is the value equal to 3:  [False  True]


## Convert array

#### Convert datatype of array:
First create list of lists and create array with dtype of float

In [6]:
num_list = [[0,1,2], [3,4,5], [6,7,8]]
arr2d = np.array(num_list, dtype='float')
arr2d

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

Then, convert to 'int' datatype

In [7]:
arr2d.astype('int')

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Convert array to list

In [8]:
my_array = np.array([1,2,3,4,5])
my_array.tolist()

[1, 2, 3, 4, 5]

### Inspecting an array

In [9]:
list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]
arr2 = np.array(list2, dtype='float')
arr2

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [10]:
# Shape
arr2.shape

(3, 4)

In [11]:
# dtype
arr2.dtype

dtype('float64')

In [12]:
# size
arr2.size

12

In [13]:
# Number of dimensions
arr2.ndim

2

### Extracting specific items from an array

- You can extract specific portions on an array using indexing starting with 0, something similar to how you would do with python lists.
- But unlike lists, numpy arrays can optionally accept as many parameters in the square brackets as there is number of dimensions.

In [14]:
list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]
arr2 = np.array(list2, dtype='float')
arr2

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [15]:
# Extract the first 2 rows and columns
arr2[:2, :2]

array([[1., 2.],
       [3., 4.]])

Additionally, numpy arrays support boolean indexing. A boolean index array is of the same shape as the array-to-be-filtered and it contains only True and False values. The values corresponding to True positions are retained in the output.

In [16]:
arr2 > 5

array([[False, False, False, False],
       [False, False, False,  True],
       [False,  True,  True,  True]])

### Reversing an array

In [17]:
arr1 = np.array([1,2,3,4,5])
arr1[::-1]

array([5, 4, 3, 2, 1])

In [18]:
list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]
arr2 = np.array(list2, dtype='float')
arr2

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [19]:
# Reverse only the row positions
arr2[::-1, ]

array([[5., 6., 7., 8.],
       [3., 4., 5., 6.],
       [1., 2., 3., 4.]])

In [20]:
arr2[::-1, ::-1]

array([[8., 7., 6., 5.],
       [6., 5., 4., 3.],
       [4., 3., 2., 1.]])

### How to represent missing values and infinite?

- Missing values can be represented using np.nan object, while np.inf represents infinite.

In [21]:
# Insert a nan and an inf

list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]
arr2 = np.array(list2, dtype='float')
arr2[1,1] = np.nan  # not a number
arr2[1,2] = np.inf  # infinite
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3., nan, inf,  6.],
       [ 5.,  6.,  7.,  8.]])

In [22]:
# Replace nan and inf with -1. Don't use arr2 == np.nan

missing_bool = np.isnan(arr2) | np.isinf(arr2)
missing_bool

array([[False, False, False, False],
       [False,  True,  True, False],
       [False, False, False, False]])

In [23]:
# replaces the value where the corresponding positions in the missing bool array is equal to True
arr2[missing_bool] = -1  
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3., -1., -1.,  6.],
       [ 5.,  6.,  7.,  8.]])

## Creating a new array from an existing array

If you just assign a portion of an array to another array, the new array you just created actually refers to the parent array in memory. That means, if you make any changes to the new array, it will reflect in the parent array as well. So to avoid disturbing the parent array, you need to make a copy of it using copy(). All numpy arrays come with the copy() method.

In [27]:
arr2 = np.array([[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]], dtype='int')
arr2

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [5, 6, 7, 8]])

In [28]:
arr2b = arr2[:2, :2].copy()
arr2b

array([[1, 2],
       [3, 4]])

## Rashaping an array

Reshaping is changing the arrangement of items so that shape of the array changes while maintaining the same number of dimensions.

In [29]:
# Creating a 2d array consisting of 3 rows and 4 columns
arr2 = np.array([[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]], dtype='int')
arr2

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [5, 6, 7, 8]])

In [30]:
# reshaping the array to have 4 rows and 3 columns
arr2.reshape(4, 3)

array([[1, 2, 3],
       [4, 3, 4],
       [5, 6, 5],
       [6, 7, 8]])

## Flattening a multi-dimensional array

- Flattening will convert a multi-dimensional array to a flat 1d array. And not any other shape.
- There are 2 popular ways to implement flattening. That is using the flatten() method and the other using the ravel() method.
- The difference between ravel and flatten is, the **new array created using ravel is actually a reference to the parent array**. So, any changes to the new array will affect the parent as well. But is memory efficient since it does not create a copy.


In [31]:
arr2 = np.array([[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]], dtype='int')
arr2

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [5, 6, 7, 8]])

In [32]:
arr2.flatten()

array([1, 2, 3, 4, 3, 4, 5, 6, 5, 6, 7, 8])

## Creating sequences, repetitions and random numbers

#### Sequence:
- The np.arange function comes handy to create customised number sequences as ndarray.

In [33]:
# array of numbers 0-4
np.arange(5)

array([0, 1, 2, 3, 4])

In [47]:
# array of numbers 5-9
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [35]:
# array of numbers 0-9 with a step of 2
np.arange(0, 10, 2)  

array([0, 2, 4, 6, 8])

In [36]:
# array of 10 to 1, decreasing
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

- We can set the starting and end positions using **np.arange**, but if you are focused on the number of items in the array you will have to manually calculate the appropriate step value. 
- Say we want to create an array of exactly 10 numbers between 1 and 50. How would we do that?
    - ANSWER: **np.linspance()**

In [37]:
# Start at 1 and end at 50
np.linspace(start=1, stop=50, num=10, dtype=int)

array([ 1,  6, 11, 17, 22, 28, 33, 39, 44, 50])

### Repeating sequences

- **np.tile()** will repeat a whole list or array n times.
- **np.repeat()** repeats each item n times.

In [38]:
arr = [1,2,3]
print ('arr:    ', arr)
print('Tile:   ', np.tile(arr, 2))
print('Repeat: ', np.repeat(arr, 2))

arr:     [1, 2, 3]
Tile:    [1 2 3 1 2 3]
Repeat:  [1 1 2 2 3 3]


### Generating random numbers

The random module provides nice functions to generate random numbers (and also statistical distributions) of any given shape.

In [39]:
# Random numbers between [0,1) of shape 2,2
np.random.rand(2,2) * 100

array([[31.683582  , 72.88622307],
       [89.48382231, 19.36895201]])

In [40]:
# Normal distribution with mean=0 and variance=1 of shape 2,2
np.random.randn(2,2)

array([[-1.84180822,  1.65550703],
       [-1.57445479,  0.18611919]])

In [41]:
# Random integers between [0, 10) of shape 2,2
np.random.randint(0, 10, size=[2,2])

array([[3, 4],
       [5, 6]])

In [42]:
# One random number between [0,1)
np.random.random()

0.9544592914906894

In [43]:
# Random numbers between [0,1) of shape 2,2
np.random.random(size=[2,2])

array([[0.16000537, 0.89659097],
       [0.9296281 , 0.197352  ]])

In [44]:
# Pick 3 items from a given list, with equal probability
# An item can be picked several times
np.random.choice(['a', 'e', 'i', 'o', 'u'], size=3)

array(['u', 'i', 'i'], dtype='<U1')

### Create array with zeroes or ones

In [49]:
print(' 5 zeroes: ', np.zeros(5))
print(' 5 ones: ', np.ones(5))

 5 zeroes:  [0. 0. 0. 0. 0.]
 5 ones:  [1. 1. 1. 1. 1.]


### Unique items

- The **np.unique()** method can be used to get the unique items

In [45]:
# Create random integers of size 10 between [0,10)
np.random.seed(100)
arr_rand = np.random.randint(0, 10, size=10)
arr_rand

array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2])

In [46]:
uniqs, counts = np.unique(arr_rand, return_counts=True)
print("Unique items : ", uniqs)
print("Counts       : ", counts)

Unique items :  [0 2 3 4 5 7 8]
Counts       :  [1 2 1 1 1 2 2]
